""" Functions related to crystallography
"""

import numpy as np

# Coordinates of points in a FCC lattice
#   Only including points that will not be generated by another unit cell 
#   after translation in a positive direction
FCC_points = np.array([
    [0.0, 0.0, 0.0],
    [0.5, 0.5, 0.0],
    [0.5, 0.0, 0.5],
    [0.0, 0.5, 0.5]
])
# Coordinates of points in a HCP lattice
HCP_points = np.array([
    [0.0, 0.0, 0.0],
    [2/3, 1/3, 1/2]
])

def euler_R(euler_angles):
    """ Convert Euler angles to a rotation matrix
    euler angles (length 3 iterable): [phi1, Phi, phi2] (rad) 
    Uses the Bunge euler angle sequence: 3-1-3
    """
    alpha, beta, gamma = euler_angles
    
    # ZXZ Euler angle rotation matrices
    Rz_alpha = np.array([
        [np.cos(alpha), -np.sin(alpha), 0],
        [np.sin(alpha), np.cos(alpha), 0],
        [0, 0, 1]
    ])
    
    Rx_beta = np.array([
        [1, 0, 0],
        [0, np.cos(beta), -np.sin(beta)],
        [0, np.sin(beta), np.cos(beta)]
    ])
    
    Rz_gamma = np.array([
        [np.cos(gamma), -np.sin(gamma), 0],
        [np.sin(gamma), np.cos(gamma), 0],
        [0, 0, 1]
    ])
    
    # Combined rotation: R = Rz(gamma) * Rx(beta) * Rz(alpha)
    R = Rz_gamma @ Rx_beta @ Rz_alpha
    
    return R

def FCC_basis(lattice_prms, euler_angles=np.zeros(3)):
    """ Basis vectors for the principal axes of an FCC lattice
    Rotated into physical coordinates
    """
    R = euler_R(euler_angles)
    # The rows of basis_vectors represent the principal directions, 
    #   [100], [010], and [001]
    basis_vectors = np.diag(lattice_prms) @ R.T
    return basis_vectors

def HCP_basis(lattice_prms, euler_angles=np.zeros(3)):
    """ Basis vectors for the principal axes of an HCP lattice
    Rotated into physical coordinates
    """
    a, b, c = lattice_prms
    if a != b:
        print("WARNING: Ignoring b. For HCP, a=b")
    R = euler_R(euler_angles)
    # lattice vectors in the crystal frame (rows)
    h1 = np.array([a, 0.0, 0.0])
    h2 = np.array([-a/2, a * np.sqrt(3)/2, 0.0])
    h3 = np.array([0.0, 0.0, c])
    basis_vectors = np.vstack([h1, h2, h3]) @ R.T
    return basis_vectors

def Ncells_fit_sphere(basis_vectors, D):
    """ Calculate the number of cells required in each direction to fit a 
    sphere of diameter D
    
    basis_vectors (3x3 np array): The rows represent the principal directions, 
        scaled by the length of the unit cell in that direction
    """
    # Calculate side lengths (lattice parameters)
    cell_lengths = np.sqrt(np.sum(basis_vectors**2, axis=1))
    # Calculate lattice angles
    alpha = np.arccos(np.dot(basis_vectors[1,:], basis_vectors[2,:]) / 
        (cell_lengths[1]*cell_lengths[2]))
    beta = np.arccos(np.dot(basis_vectors[0,:], basis_vectors[2,:]) / 
        (cell_lengths[0]*cell_lengths[2]))
    gamma = np.arccos(np.dot(basis_vectors[0,:], basis_vectors[1,:]) / 
        (cell_lengths[0]*cell_lengths[1]))
    # Calculate constraints on side lengths
    Lmin_alpha = D / np.sin(alpha)
    Lmin_beta = D / np.sin(beta)
    Lmin_gamma = D / np.sin(gamma)
    # Calculate required side lengths
    Lx = max(Lmin_beta, Lmin_gamma)
    Ly = max(Lmin_alpha, Lmin_gamma)
    Lz = max(Lmin_alpha, Lmin_beta)
    # Convert side lengths to number of cells in each direction
    N_cells = np.ceil(np.array([Lx, Ly, Lz]) / cell_lengths).astype(int)
    return N_cells

def generate_lattice(lattice_type, domain, lattice_prms, euler_angles):
    """ Generate coordinates of an FCC lattice filling the given domain
    
    lattice_type (str): FCC or HCP
    domain (3x2 np array): [(xmin, xmax), (ymin, ymax), (zmin, zmax)]
    lattice_prms (length 3 iterable): [a, b, c]
    euler angles (length 3 iterable): [phi1, Phi, phi2] Bunge euler angles
    
    Strategy: Generate a rhombic prism big enough to fit a sphere with diameter
        equal to the longest diagonal in domain, then center that lattice in 
        the domain, then remove points outside of the domain
    """
    domain = np.array(domain)
    lattice_prms = np.array(lattice_prms)
    if lattice_type == "FCC":
        # Points in the FCC lattice
        lattice_points = FCC_points
        # Principal direction vectors
        basis_vectors = FCC_basis(lattice_prms, euler_angles)
    elif lattice_type == "HCP":
        # Points in the HCP lattice
        lattice_points = HCP_points
        # Principal direction vectors
        basis_vectors = HCP_basis(lattice_prms, euler_angles)
    else:
        print("ERROR: Unrecognized lattice_type")
    # Determine the longest diagonal of the domain
    lengths = domain[:,1] - domain[:,0]
    L = np.sqrt(np.sum(lengths**2))
    # Number of unit cells required in each direction
    N_cells = Ncells_fit_sphere(basis_vectors, L)
    # Number of points per unit cell
    N_ppc = lattice_points.shape[0]
    # Initialize coordinate array
    coords = np.empty((np.prod(N_cells)*N_ppc, 3))
    for ix1 in range(N_cells[0]):
        for ix2 in range(N_cells[1]):
            for ix3 in range(N_cells[2]):
                cell_origin = np.array([ix1, ix2, ix3]) @ basis_vectors
                cell_points = cell_origin + lattice_points @ basis_vectors
                ix_insert = (ix1*N_cells[1]*N_cells[2] + ix2*N_cells[2] + ix3)*N_ppc
                coords[ix_insert:ix_insert+N_ppc,:] = cell_points
    # Translate coordinates to center them over the domain
    domain_center = np.mean(domain, 1)
    # Could consider the fact that the last row of unit cells isn't totally full
    lattice_center = N_cells @ basis_vectors/2
    trnsl_vec = domain_center - lattice_center
    coords += trnsl_vec
    # Remove points outside of the domain
    in_domain = np.all((coords >= domain[:,0]) & (coords <= domain[:,1]), axis=1)
    coords_sub = coords[in_domain]
    
    return coords_sub

def miller_plane(miller, lattice_prms, euler_angles=np.zeros(3)):
    """ Convert miller indices to basis vectors that span the plane in physcial
    coordinates
    
    miller (length 3 iterable): [i, j, k] Miller indices
    lattice_prms (length 3 iterable): [a, b, c]
    euler angles (length 3 iterable): [phi1, Phi, phi2] Bunge euler angles
    """
    pass


if __name__ == "__main__":
    # Testing

    domain = np.array([(-8, 8), (-5, 5), (-3, 3)])
    lattice_prms = np.array([8, 6, 4])
    euler_angles = np.array([0.1, 0, 0]) #np.pi/6, np.pi/4])
    generate_lattice("FCC", domain, lattice_prms, euler_angles)
